### PR TITLE
Updating MYNN-EDMF submodule, including file name changes that conform to WRF standards

### PR DESCRIPTION
**Pull request by joeolson42**
This PR updates the MYNN-EDMF submodule. The main changes are:

1. Removal of the RH-based cloud fraction component in the stratus subgrid clouds
2. Implemented some tuning parameters to reduce subgrid clouds in the PBL, especially near the surface over water and ice.
3. Some misc mods include: (a) adding the less-restricted MF activation over water (from RRFSv1/CCPP), (b) a clean-up of the mixing length scale adaptivity, which only impacts near LES scales, (c) adding the "hrrrv5" option to the suite flag description in the Registry (no impact, just documentation).

Some results of this testing can be found in the attached pdf.
[Updates to MYNN-EDMF submodule (09 Dec 2024).pdf](https://github.com/user-attachments/files/18067043/Updates.to.MYNN-EDMF.submodule.09.Dec.2024.pdf)

This code is already running in the realtime WRF-WFIP3 and MPAS-dev2 on jet and has been testing in a MPAS case study. The regression tests (attached) show expected changes to the hrrrv5 suite and do not change the mesoscale_reference suite.
[compare_run_testcases_6b9226531-intdebug.txt](https://github.com/user-attachments/files/18188872/compare_run_testcases_6b9226531-intdebug.txt)

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]

**Review by mdtoyNOAA — APPROVED** [review]

**Comment by joeolson42** [comment]
I added the precision fix from Mike Barlage to the MYNN-EDMF submodule and updated this PR.  One less separate PR to make.

**Comment by barlage** [comment]
@joeolson42 do you want us to review your MYNN code as well?

**Comment by joeolson42** [comment]
It already has 2 reviews, but one more won't hurt. It's a fairly straight-forward set of code changes.

**Comment by barlage** [comment]
I don't exactly know what the best solution is for these errors we get with the gnu compiler. It seems the main issue is that the precision of the arguments should be the same, but with the use of `kind_phys` this could get complicated. So, in your case, the proposed line is

`gmelq = max(real(gmel/q3sq), 1e-8_kind_phys)`

the code has `gmel` and `q3sq` hard coded as doubles, so with `kind_phys` as single, then we need the `real` so that the arguments have the same precision. But if `kind_phys` is double, then will there be a mismatch again?

**Comment by joeolson42** [comment]
What about this?

gmelq = max(real(gmel/q3sq, kind_phys), 1e-8_kind_phys)
and
real(kind_phys):: gmelq

That should be bullet proof, right?

**Comment by barlage** [comment]
Yes, putting kind_phys in the real statement is probably the correct way to do this.

**Comment by joeolson42** [comment]
OK, now this PR is smoking hot and ready to go!

**Comment by barlage** [comment]
We should know in about an hour what test cases you need to run with the final code :)

**Comment by joeolson42** [comment]
Regression tests have been run and (successful) output is now attached. This PR should be ready to merge.

**Review by barlage — APPROVED** [review]
Test results look good. Those q2, t2m, th2m are somewhat random and hopefully will be solved with the mesoref reproduce fix.

**Pull request merged**
