### PR TITLE
Fix idealized cases

### PR DESCRIPTION
**Pull request by AndersJensen-NOAA**
#48 breaks the idealized MPAS cases. @tanyasmirnova please confirm this is the fix.

### CODE REVIEW

**Review by tanyasmirnova — COMMENTED** [review]
@AndersJensen-NOAA Thank you for this fix. I have done the same change in my PR, but also moved shdmin, shdmax to the 'first-guess' block.

**Comment by jderrico-noaa** [comment]
@AndersJensen-NOAA should this go in before PR #49?

**Comment by AndersJensen-NOAA** [comment]
> @AndersJensen-NOAA should this go in before PR #49?

@jderrico-noaa @tanyasmirnova This can go in before #49. #49 now includes this change with a slight refactor.

**Comment by tanyasmirnova** [comment]
> > @AndersJensen-NOAA should this go in before PR #49?
> 
> @jderrico-noaa @tanyasmirnova This can go in before #49. #49 now includes this change with a slight refactor.

@jderrico-noaa Anders has a fix for #49, therefore it should go after #49. Or we can just do #49 without #50 because I put a fix into my PR.

**Pull request merged**
